services:
  site:
    build: .
    ports:
      - "4000:4000"
      - "35729:35729"   # livereload
    volumes:
      - .:/srv/jekyll
      - gems:/usr/local/bundle
    command: bundle exec jekyll serve --host 0.0.0.0 --force_polling --livereload

volumes:
  gems:
